### ISSUE TITLE
Configuring `--enable-shared` does not work on Windows

### ISSUE THREAD

**Issue by lsorber** [coin-or/Cbc#189]
The `--enable-shared` parameter is ignored on Windows (using the MSYS2 toolchain), resulting in `checking whether to build shared libraries... no` even though the user explicitly asks for shared libraries.

According to this SO question [1], regenerating `configure` with a newer version of Autotools solves the problem (the current configure scripts appear to be from 2007).

[1] http://stackoverflow.com/questions/14635871

**Comment by lsorber** [comment]
Is this issue resolved?

**Comment by svigerske** [comment]
There is work in progress that will resolve this, but progress is slow. There is nothing we will do particularly for Cbc before the upgrade of the autotools will happen. For building DLLs in particular, a lot of code needs to be touched as well.
One could also say that this issue here is a duplicate of coin-or-tools/BuildTools#112.

**Comment by lsorber** [comment]
So if https://github.com/coin-or-tools/BuildTools/issues/112 is resolved, does that automatically resolve this issue?

**Comment by svigerske** [comment]
Yes, it will be resolved in the autotools-update branch first, which should be merged into master later.
