### ISSUE TITLE
`pkg-config` configuration not Windows-compatible

### ISSUE THREAD

**Issue by lsorber** [coin-or/Cbc#191]
The `configure` scripts set the environment variable `PKG_CONFIG_PATH` (needed by the `pkg-config` tool) as a colon-delimited set of paths. E.g.,

```bash
PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH:$COIN_PKG_CONFIG_PATH_UNINSTALLED"
export PKG_CONFIG_PATH
```
and
```bash
IFS=":"
for dir in $COIN_PKG_CONFIG_PATH_UNINSTALLED ; do
  [...]
```

However, on Windows `pkg-config` expects the paths to be semi-colon separated:
> pkg-config retrieves information about packages from special metadata files. These files are named after the package, with the extension .pc. By default, pkg-config looks in the directory prefix/lib/pkgconfig for these files; it will also look in the colon-separated (**on Windows, semicolon-separated**) list of directories specified by the PKG_CONFIG_PATH environment variable.

Because of this, `configure` fails with the default parameters. A workaround is to set `--disable-pkg-config`.

**Comment by tkralphs** [comment]
@lsorber Can you give more details about when this arises. On Windows, pkg-config is problematic if you are not careful because there are versions that expect Posix paths (the ones that come with WSL and MSys2) and versions that expect Windows paths (there is at least one stand-alone binary built for Windows). I believe the versions that understand Posix paths should also expect a semi-colon separated list of paths. Any environmet in which you are running `configure` must have `bash` and I would then expect a version of `pkg-config` that works well to be provided. I am regularly building on Windows with `pkg-config` in MSys2 and WSL. I guess maybe you have a stand-alone version of `pkg-config` in your `PATH` that understands Windows paths? It would be good to work this out and understand what is happening so we can perhaps detect the compatibility of the user's `pkg-config` and automatically disable usage when it doesn't understand Posix paths.

**Comment by tkralphs** [comment]
This is really a problem with [BuildTools](https://github.com/coin-or.tools/BuildTools), not Cbc, but I can't transfer the issue over to that repo, since the build system is technically maintained in a different Github organization. We can just leave it here for now, but @LouHafer might also want to know about this issue.

**Comment by LouHafer** [comment]
Noted. This (adaptation to Windows path syntax) is likely a more general problem. I'll keep it in mind when I'm back in BuildTools mode. (Currently diverted to OSI2 for a bit.) Much to my annoyance, Windows build environments (WSL, Msys) are at the top of my BuildTools todo list. @lsorber, per Ted's comment, details of your build environment would be helpful. I'm actually working on the BuildTools update (master) branch but good to be aware of potential problems.

**Comment by tkralphs** [comment]
@lsorber I've made sure now that setting --disable-pkg-config works well with `coinbrew`. For the foreseeable future, using `--disable-pkg-config` will be the recommended way to proceed when the Windows version of `pkg-config` is present. Do you know if there is a way we can programmatically detect that we are using the Windows version of `pkg-config`? That way, it can just be ignored at configure time and everything should work fine.

**Comment by lsorber** [comment]
I was also using the disable package config workaround at the time I submitted this issue. I wouldn't know of a better solution than to just check if the current platform is Windows and if so, to disable package config.

**Comment by tkralphs** [comment]
Just checking the platform doesn't work because the versions of pkg-config that come with WSL, MSys2, and CYGWIN understand posix paths and work fine. It is also possible to be using an incompatible version of pkg-config even if you are on those platforms, depending on your PATH. I guess there should be a relatively easy test to see what version is being used. I will look into it.

**Comment by svigerske** [comment]
There will be no support for pkg-config with Windows paths.

**Comment by tkralphs** [comment]
I would still like to think about this a bit, but I guess I could open another issue for it, since what I have in mind is a bit different than what this issue is getting at.
