### ISSUE TITLE
Feasibility pump does not find feasible solution any more on CBC >= 2.10.0

### ISSUE THREAD

**Issue by lapseofreason** [coin-or/Cbc#219]
I am working with a series of IP instances where CBC < 2.10.0 consistently was able to find initial feasible solutions using feasibility pump. CBC >= 2.10.0 on the other hand fails to find an initial feasible solution during the heuristics phase for any of the instances.

I have tested this on multiple (similar) instances with versions **2.7.5**, **2.9.8** and **2.9.10** (partially on Linux and on Windows), all of which report an **initial feasible solution is found by feasibility pump**. Both versions **2.10.0** and **trunk** (fc070c9) **fail to find a feasible solution during the heuristics phase**. All of the tests were done using the command line interface with default settings (except for time limit). I have attached two of the logs for reference:
[cbc-2.9.8.log](https://github.com/coin-or/Cbc/files/3107873/cbc-2.9.8.log)
[cbc-fc070c9.log](https://github.com/coin-or/Cbc/files/3107874/cbc-fc070c9.log)

I am aware that heuristics are not guaranteed to find a feasible solution for an instance, but since I consistently got the same result with different versions/instances, I was wondering whether this might be a bug.

Have there been any changes to feasibility pump that this might be related to? Or maybe there has been a configuration change with 2.10? If yes, is it possible to get the old behaviour back through the parameters?

**Comment by jjhforrest** [comment]
It looks as if trunk is more likely to make slacks, which must take 
integer values because of constraint, into integer variables.

This can improve search by giving extra flexibility as to where to 
branch.  But for heuristics and especially the feasibility pump, this is 
probably not a good idea.

I have modified trunk so that all zero cost singleton integer variables, 
which will automatically take integral values if all other variables in 
constraint take integral values, are made continuous for many heuristics 
including feasibility pump.

Has that helped?

John Forrest

**Comment by lapseofreason** [comment]
I was only able to try it one one instance today, but for that it worked great, even better than the heuristic from 2.9.8:
[cbc-3ffc468.log](https://github.com/coin-or/Cbc/files/3123747/cbc-3ffc468.log)

I can test it on more instances on Monday and then close the bug.

Thanks a lot!

**Comment by lapseofreason** [comment]
I did some more testing and the heuristics found feasible solutions for all of the instances that I previously had problems with using cbc 2.10. So commit 46c128d fixed this, thanks!
