### ISSUE TITLE
Missing treeStatus event when solving small problem

### ISSUE THREAD

**Issue by akazachk** [coin-or/Cbc#292]
Dear all,

I think there may be an issue with the new if statement here: https://github.com/coin-or/Cbc/blob/8d4e60efe7a2b495b671b25706fdf0a78514d502/src/CbcModel.cpp#L4772

compared to the old version of that statement: https://github.com/coin-or/Cbc/blob/64a3087bd1159804d41b65d0cc5bc9cdf5b7a25f/Cbc/src/CbcModel.cpp#L4735

Namely, I think that when solving a small problem (e.g., bm23), the extra condition `CoinWallclockTime()-lastSecPrintProgress_ > secsPrintFrequency_` evaluates to false, which results in the user never encountering the `treeStatus` event on line 4846: https://github.com/coin-or/Cbc/blob/8d4e60efe7a2b495b671b25706fdf0a78514d502/src/CbcModel.cpp#L4846

**Comment by svigerske** [comment]
I would interpret the change (addition of check against `secsPrintFrequency_`) as a modification of what is meant by "A tree status interval has arrived." in the documentation for `CbcEvent::treeStatus`.
Before the interval was defined by the number of nodes that have been passed, now it is also the time since the last print.

I don't say that this new behavior is better concerning the treeStatus event. It was probably added by someone who had only the log output in mind. But calling `CbcModel::setSecsPrintFrequency(-1)` should restore the previous behavior.

**Comment by akazachk** [comment]
Agreed that this fixes it temporarily. We can close this issue. However you may wish to keep it open because, for the future, I think it would be better to disentangle the `treeStatus` event from the log output frequency, especially as users should have access to the `treeStatus` event. E.g., my event handler collects some information at the `treeStatus` event, which it later uses when encountering a `node` event.

**Comment by svigerske** [comment]
My understanding is that the "tree status interval" is meant to be synonymous to the log output frequency.

It would certainly make sense to have some event to be called at every node, or after every LP solve, etc. I'll leave that to the Cbc developers to consider.
