### ISSUE TITLE
Obtaining duals for LP on Cbc - Clp's performance lagging

### ISSUE THREAD

**Issue by DLC49** [coin-or/Cbc#301]
Hello team,

I have been testing Cbc. I obtain a great performance, Cbc even outperforms some commertial solvers in some numerically complex problems. 

But it does not deliver dual variables. Is there a way of obtaining them?

I have tried Clp but somehow its performance is lagging at least 20 times Cbc's.

Thank you!

**Comment by jjhforrest** [comment]
Can you give some more details.

On 30/04/2020 21:48, DiegoLTC wrote:
> Hello team,
> 
> I have been testing Cbc. I obtain a great performance, Cbc even 
> outperforms some commertial solvers in some numerically complex problems.
> 
> But it does not deliver dual variables. Is there a way of obtaining them?
>
If using standalone solver then setting -printing all will give more 
information.


> I have tried Clp but somehow its performance is lagging at least 20 
> times Cbc's.

Does the problem that you are solving have integer variables?  If so 
then Clp will only give continuous optimum - but should take much less 
time.  If not - then Cbc is just using Clp so Cbc must be setting 
something to make it go faster - some output would help.

John Forrest

**Comment by DLC49** [comment]
Thank you John,

The problem I am trying to solve has no integer variables.

See the log files from three processes I have executed using the Julia interface.
- Clp short: takes 415 seconds, presolve leaves 78723 rows
- Cbc short: takes less than 8 seconds, presolve leaves 78723 rows 
- Cbc long: takes 112 seconds

The times of Cbc are great, but those of Clp are somehow excessive. 

Correct me if I am wrong, but after looking at the log files the extra time needed by Clp seems to be partially due to some overhead time but not only. If it is overhead, do you think that overhead time would be on the Clp side or on the wrapper side?

I have also tried running it directly (no wrapper) from Clp, but I am unable to import it as mps file (zip file attached) as it reads: 

Bad image at line ...
Bad image at line ...
Returning as too many errors
There were 100001 errors when importing model from c:\test_7.mps
There were 100001 errors on input

Any idea?

Thank you in advance

[Cbc long.txt](https://github.com/coin-or/Cbc/files/4567677/Cbc.long.txt)
[Cbc short.txt](https://github.com/coin-or/Cbc/files/4567678/Cbc.short.txt)
[Clp short.txt](https://github.com/coin-or/Cbc/files/4567679/Clp.short.txt)

[short.zip](https://github.com/coin-or/Cbc/files/4567687/short.zip)

**Comment by jjhforrest** [comment]
Diego,

The problem seems to be in Julia - or at least before the code gets to 
Clp.  The time reported in Clp is only 14.4 (plus 1.3 for presolve). 
This is twice the Cbc time, but that is because the Clp program guessed 
incorrectly that it should use primal.  If I tell Clp to use dual, I get 
same run as your Cbc one.

I have not got the energy to dig into the Julia interfaces, but the Cbc 
version does not seem to have add_row or add_column so does things in a 
different way.  The Clp version has both add_row and add_rows.  If the 
interface is using add_row and/or add_column, then that would explain 
the large time spent before Clp.  There is an example in 
Clp/examples/addRows.cpp which which is there just to explain why it is 
not a good idea to add one row at a time for many rows.

John Forrest

**Comment by DLC49** [comment]
Thank you John, very helpful!
