### ISSUE TITLE
Solve multiple problems (different models) in parallel 

### ISSUE THREAD

**Issue by uurriola** [coin-or/Cbc#304]
Hi,

I work in a parallel environment in python and I want to solve separate/different models in each of these threads/processes. 

The issue is that I get different results when solving sequentially and in parallel. Looks like call to "solve" is not thread-safe (not even process-safe!). Do you have any insight about that?

I found this thread from 2013 saying solving multiple models is possible but depends on the way CBC is called: [Thread safety](https://list.coin-or.org/pipermail/cbc/2014-June/001356.html) 

On another thread, someone (John Forrest) pushed an update to allow parallel use with ORTools : [thread safe usage of CBC](https://list.coin-or.org/pipermail/cbc/2013-December/001201.html).

Alos, @h-g-s , you mentioned a year ago that CBC itself was not 100% thread-safe (in [this issue](https://github.com/coin-or/Cbc/issues/223)), is that still true?

I can try to create a small example if necessary. 
Thx

**Comment by uurriola** [comment]
I tried to reproduce without success today. Let's close this

**Comment by shaurakar** [comment]
Hello Everyone,

I am also facing exactly the same issue but in c++. I use CBC solver embedded in GOOGLE OR (c++ platform). I am using it for solving the mixed integer linear programming problem.
I am following the sample code shown in the Google OR website [https://developers.google.com/optimization/mip/integer_opt](url)

However, I have a bunch of threads(pthreads)/threadpool that are trying to call solver (CBC) simultaneously. All of the threads have thread local data, and hence are calling the solver on their local data simultaneously. This also means that I am ensuring that the constraints, MPSolver, etc are all thread local (none of them are global). Objective is to solve multiple MILP problems in parallel. Each problem is solved by a thread by calling its own CBC solver (thread local).

**Problem:** If 'n' threads call the solver simultaneously, i see that the solver reports "No Solution Found" for all the thread local datasets. However, if the whole process is sequential i.e. different datasets are solved one after another by limiting the number of threads to 1 (means no multiple cbc solvers, only one), then I get perfect optimal solution for each and every datasets. Now, this happens only when the time limit has been set to a finite value. The time limit is set to 5s using the api solver.SetTimeLimit(). I can't avoid setting the time limit because there can be cases where it might take huge amount of time to get the optimal solution. Different threads can have different data sets which can be varying in size (number of constraints and number of variables). 'n' varies from 2 to 32

Note: Just to re-clarify I am trying to invoke simultaneously 'n' solver calls using 'n' threads (each thread calls it's own solver.solve()).
I am not trying to distribute the work of a single solver among 'n' threads. All I am trying to do is to run multiple CBC solvers in parallel and each solver is being handled by a different thread.

I posted the same question in stack overflow nearly 2 months back. [https://stackoverflow.com/questions/61867301/running-multiple-instances-of-google-or-solver-cbc-results-in-no-solution-foun](url)
Thanks

**Comment by dlaehnemann** [comment]
It seems like there is a workaround for this problem when you build from source, and a solution in the making:
https://github.com/coin-or/Cbc/issues/332#issuecomment-786570533
