### ISSUE TITLE
 How to know if an LP problem has multiple optimal solutions? 

### ISSUE THREAD

**Issue by cecilecro** [coin-or/Cbc#313]
I would like to know if an LP problem has multiple optimal solutions, is there a simple manner to check that with the results of the cbc solver?

Thanks for your help.

**Comment by jjhforrest** [comment]
You posted to Clp and Cbc.  If it is an integer problem i.e. Cbc, then 
it is not easy.  For a continuous problem i.e. Clp it is easier - but 
not trivial (I am assuming you want a solution with different primal 
values - not just a different basis).

John Forrest

**Comment by cecilecro** [comment]
Yes I posted in both repositories because I use the cbc solver but for solving a continuous problem, so I finally use Clp through Cbc if i'm not mistaken. I just specified my first comment and the title of the issue.

I'm not necessarily searching for others optimal solutions, I just want to know if there exist a unique solution or multiples for my problem.

**Comment by jjhforrest** [comment]
There may be a better way - but - one could easily write a program that -
a) Sees if any variables/slacks at bounds have reduced costs of zero.
b) If none, then no other solution exists - otherwise
c) Make the objective a constraint to keep objective same and then for 
each such variable/slack give it a cost of + or - 1 and solve that 
problem.  One could use a Clp event handler to see if anything moved at 
each iteration and if so then stop - declaring that there was an 
alternative solution - or you could just solve to end.

John Forrest

**Comment by cecilecro** [comment]
Thank you for your reply !
I use Pyomo to model and solve problems, I will adapt this methodology to this case.
