### ISSUE TITLE
cbc running parallel in single-thread mode

### ISSUE THREAD

**Issue by ssche** [coin-or/Cbc#366]
I noticed that cbc is running in parallel even though is was not compiled with `--enable-cbc-parallel`. The full command is `cbc problem.mps presolve on allow 1 maxN 80000 branch printingOptions all`. The threads (or processes) are dynamically created throughout the run and increase and decrease. I don't mind that cbc runs in parallel, but on the server there are multiple cbc calls being executed at the same time and with all of those runs creating threads, the system is becoming very unresponsive. Is there a way to control the behaviour to restrict the number of threads/processes that are run in parallel?

**Comment by tkralphs** [comment]
In the `master` branch, the parallel executable is built automatically when `pthreads` is available unless you explicitly disable that with `--disable-cbc-parallel`. This is not the case in earlier versions. But you should always be able to do `threads 1` to limit to one thread.

**Comment by orrery** [comment]
For cbc from https://www.coin-or.org/download/source/Cbc/Cbc-2.10.5.tgz built in Ubuntu 16.04 if `apt-get install libopenblas-dev -y` openBLAS dev library is installed (which uses pthreads), I found that cbc  is built as a parallel executable. Also, the `threads` option is not available in `cbc` console despite being a implicit parallel executable build due to the presence of pthreads via openBLAS. Is this expected behaviour?
With consideration for the above, in 2.10.5 would I have to explicitly configure the build with the `--enable-cbc-parallel` in order to be able to set `threads 1` ?

**Comment by svigerske** [comment]
Cbc does not check whether the linear algebra library is mulitithreaded and does not attempt to control the number of threads used in there, as far as I know.

So maybe try setting OPENBLAS_NUM_THREADS=1 in your environment then.

It could well be that the `threads` option of Cbc isn't available if it has been build without enabling parallelism in Cbc. Should be easy to try out whether the option is accepted.

**Comment by jjhforrest** [comment]
Try adding -DCLP_USE_OPENBLAS=1 to ADD_CXXFLAGS="" in the build.

**Comment by orrery** [comment]
Thank you for your help gentlemen, I observed the following, after trying your suggestions:

> It could well be that the threads option of Cbc isn't available if it has been build without enabling parallelism in Cbc. Should be easy to try out whether the option is accepted.

It appears that `--enable-cbc-parallel` is necessary in order to have the `threads` option in cbc command line (which I think is consistent with the cbc documentation), but setting it to 1 still results in all cores being utilised. 

> In the master branch, the parallel executable is built automatically when pthreads is available unless you explicitly disable that with --disable-cbc-parallel. This is not the case in earlier versions. But you should always be able to do threads 1 to limit to one thread.

It appears even with `threads 1` all cores are still utilised.

> Try adding -DCLP_USE_OPENBLAS=1 to ADD_CXXFLAGS="" in the build.

```
wget https://www.coin-or.org/download/source/Cbc/Cbc-2.10.5.tgz
tar xvfz Cbc-2.10.5.tgz
cd Cbc-2.10.5
mkdir build
cd build
../configure --enable-cbc-parallel ADD_CXXFLAGS="-DCLP_USE_OPENBLAS=1 -L/usr/lib -lopenblas" <- link with installed openBLAS https://github.com/xianyi/OpenBLAS/releases/download/v0.3.13/OpenBLAS-0.3.13.zip
make
make install
```

I can now specify threads effectively and now I see the expected number of cores being utilised.
```
./cbc./test.mps threads 2 max presolve on randomCbcSeed 42 randomSeed 42 allow 1 maxN 80000 branch printingOptions all
```
This appears to have resolved the issue, and now only the specified number of cores are utilised. @jjhforrest does your suggestion relate to this fix? https://projects.coin-or.org/Clp/changeset/2083
