### ISSUE TITLE
cbc installation problem

### ISSUE THREAD

**Issue by Afraz85** [coin-or/Cbc#486]
Hi,
I am trying to install cbc with following commands: brew tap coin-or-tools/coinor
brew install coin-or-tools/coinor/cbc
But I am unable to configure it. When I write cbc on my Terminal  I get following:
**_dyld[63849]: Symbol not found: _cbc_glp_prob
Referenced from: /usr/local/Cellar/cbc/2.10.7_1/lib/libCbcSolver.3.10.7.dylib
 Expected in: /usr/local/Cellar/coinutils/2.11.6/lib/libCoinUtils.3.11.6.dylib
zsh: abort      cbc_**

I also trying to test cbc with other command of python package: % oemof_installation_test
but I get following:
*****************************
Solver installed with oemof:

cbc: not working
glpk: working
gurobi: not working
cplex: not working

*****************************
oemof successfully installed.
*****************************
and similarly the codes with calling of cbc solver are also not executable.
waiting for positive response. Thanks in advance

**Comment by tkralphs** [comment]
I cannot replicate this and there seem to be other people managing to use it successfully. The error you're seeing would arise if CoinUtils were not compiled with GMPL support, but Cbc is. Can you try reinstalling CoinUtils? If you add `--verbose` and attach the output as a file here, I may be able to see something.

**Comment by Afraz85** [comment]
@tkralphs , thanks for helping me out. Can you please check the output.

**Comment by Afraz85** [comment]
@tkralphs . thanks for the comments. Please see the file
[Terminal Saved Output.txt](https://github.com/coin-or/Cbc/files/8288035/Terminal.Saved.Output.txt)
.

**Comment by tkralphs** [comment]
You have to either do `brew reinstall` or else `brew uninstall` followed by `brew install` to get useful output.

**Comment by Afraz85** [comment]
HI @tkralphs , I followed the steps. After brew install it asked me to add the path. I did that by using nano ~/.zhrc    . It seems that path is added but still it does not recognising. Please  see the attached output,
[Terminal Saved Output_af.txt](https://github.com/coin-or/Cbc/files/8303028/Terminal.Saved.Output_af.txt)

**Comment by tkralphs** [comment]
Hmm, that's now a different error. Now the undefined symbol is in `libClpSolver.1.14.7.dylib`. And now you have another complication. The output shows that you uninstalled and reinstalled cbc from homebrew core rather than from the coin-or tap. This is fine, but you probably just don't want to mix and match. projects from our tap are now "keg only" because of this conflict, so you have to manually link them to use them. The mixing and matching could be the issue, I don't know I would suggest that you uninstall everything from the entire cbc stack, both from our tap and from homebrew core and then start again from scratch. It might be easiest to just install cbc from homebrew core. 
```
brew uninstall coinutils osi clp cgl cbc
brew uninstall coin-or-tools/coinor/coinutils coin-or-tools/coinor/osi coin-or-tools/coinor/clp coin-or-tools/coinor/cgl coin-or-tools/coinor/cbc
```
