### ISSUE TITLE
`coinbrew build Cbc` does not build libCbcSolve.so

### ISSUE THREAD

**Issue by natebragg** [coin-or/Cbc#541]
There is no clear way to build libCbcSolve.so, and it seems to me that `coinbrew build Cbc` ought to perform this action.  If that is not correct, then at least the README.md should be expanded to include how to build this library.

**Comment by tkralphs** [comment]
I assume you are using the `master` branch. As part of the ongoing refactoring, `libCbcSolver` has been merged into `libCbc`. There was no real purpose to the split and it only complicated the build. So if you were previously linking to `libCbcSolver`, you now just link to `libCbc` and it should just work.

**Comment by natebragg** [comment]
Thank you!  However, when I link it claims that `Cbc_printModel` is missing, and indeed I don't see it in `Cbc_C_Interface.h`.  But it seems like Cbc releases are cut from elsewhere.  Github claims "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."  Where can this repository be found?

**Comment by tkralphs** [comment]
Releases are made from the current stable branch (as described [here](https://coin-or.github.io/user_introduction#additional-useful-information)), which is `stable/2.10`. It sounds like you probably want either the `stable/2.10` branch or the latest release tag. Since you are using `coinbrew`, you can just do 
```
coinbrew fetch Cbc@2.10
```
or
```
coinbrew fetch Cbc@2.10.8
```
and then build. If you do this, then you will have `libCbcSolver`, as expected and also `Cbc_printModel`, which is part of the C interface in `stable/2.10`: https://github.com/coin-or/Cbc/blob/60331cd840d730e8f4923dab69a3ea968640ad66/Cbc/src/Cbc_C_Interface.h#L505

**Comment by natebragg** [comment]
Thank you for all your help.
