### ISSUE TITLE
CBC finds incorrectly a model to be infeasible

### ISSUE THREAD

**Issue by adrienrim** [coin-or/Cbc#562]
A MIP model should be feasible with an optimal objective value of 0. Cplex (ran from NEOS server) finds the proper solution while CBC 2.10.8 finds the model infeasible.
[failed_model.zip](https://github.com/coin-or/Cbc/files/9964763/failed_model.zip)
FYI, making all variables binary solves the issue but it should not make a difference. Thank you!

Adrien

**Comment by jjhforrest** [comment]
Seems to be an accuracy issue with CglTwomir cuts - running with debug I get
Cut with 52 coefficients, cuts off known solutions by 0.000397818, lo=-4.88577, ub=1.79769e+308
Will look into it.

**Comment by jjhforrest** [comment]
I do not understand all the coding in CglTwomir, but I think I can see the area where there may be an error.  If there is a constraint 
 0.9999 <= sum of some x <= 1.0 and the sum is at 0.9999 the cut can be bad.  If I add a slack variable so slack + sum ==1.0 the bad cut is not generated.  If I switch off preprocessing on failed_model.lp, the correct solution is reached, but with preprocessing on it fails as some constraints are changed to 0.9999 ....

A solution that can do no harm is to weaken the problem (just for CgTwomir) so that there would be no ranged constraint if it is at a non integer value.  So the constraint becomes 0.9999 <= <- infinity.

That works and does not seem to be activated on most other test problems.

If someone with more knowledge of the code could investigate - that would be good.  If not, I will probably modify the code in a day or two.

**Comment by jjhforrest** [comment]
Found the bug - in area I was fixing, but simple to fix.  Updated in stable and master

**Comment by adrienrim** [comment]
Thank you John for fixing this bug, and for all your work!
Cheers
