### ISSUE TITLE
Soversion of the shared libs has to be bumped

### ISSUE THREAD

**Issue by pgrt** [coin-or/Cbc#610]
Hello,

I am one of the maintainers of Cbc in Debian. It turns out that Release 2.10.9 or 2.10.10 increased the size of the class CbcModel, which breaks the ABI. For instance one has to rebuild Bonmin to be able to run it against Cbc 2.10.10.

Thus I think the SOVERSION of the shared libs in Cbc should be bumped from 3 to 4.

Thanks a lot,

Pierre

**Comment by jhmgoossens** [comment]
No answer, but merely my comment: Should API changes be included in such patch (3rd dot) releases like 2.10.10? I expected no API changes in these patch releases.

**Comment by svigerske** [comment]
The API hasn't changed, at least not in a backward incompatible way.

Some unused private variables were removed and, if I remember right, some members may have been added that were previously added only conditionally. This changes the ABI, so that you need to recompile an application that uses Cbc with the updated headers to use the newer library.

**Comment by pgrt** [comment]
Hi,

Thanks to both of you for the comments! I agree with you @svigerske that the addition of members broke the ABI.
Do you intend to bump the soversion in a close future? If not, then I will change it to 3.1 in Debian to trigger a rebuild of reverse dependencies until you do a bump (to 4, I guess) for other reasons.

Cheers,

Pierre

**Comment by svigerske** [comment]
I don't intend that :), but I don't know what @tkralphs or @jjhforrest intend.
We couldn't have the soversion to be calculated automatically from the version number if this is changed, I suppose.

It's probably best if you just change it in Debian if that is easy. Things aren't always moving quickly here. :)

**Comment by pgrt** [comment]
Honestly I am comfortable with introducing a Debian-specific soversion until you raise it for another reason :)

I saw the way the soversion is computed automatically and I understand you would like to stick to it!

**Comment by jhmgoossens** [comment]
Thanks to both of you. Once again, I learned something. This time API vs ABI.

**Comment by tkralphs** [comment]
So yeah, I'm getting closer to having  little bandwidth for pushing out new stables and releases that would bump the soversion. However, that won't fix the problem really, since it will be  new major version 3.0) and I guess may actually end up being a separate cbc3 package, not sure how that works. I would imagine that there will be plenty of people who want to just stick with `2.10` and the current release should be pushed out in any case. So I think the idea of a Debian-specific soversion, if it is not difficult to do and won't cause any problems, is a good solution. Thanks @pgrt for doing the packaging! That is much appreciated.

**Comment by pgrt** [comment]
Hi everyone,

Thanks for your opinions and the friendly words. I guess this issue can be closed as we came out with a solution!

Best,
Pierre
